CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    CEP VARCHAR(8),
    NUMERO VARCHAR(4) NOT NULL
);

CREATE TABLE TELEFONE (
    CPF VARCHAR(11) PRIMARY KEY,
    TELEFONE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
);

CREATE TABLE ANIMAL (
    CODANIMAL VARCHAR(10),
    CPF VARCHAR(11),
    NOME VARCHAR(20) NOT NULL,
    RACA VARCHAR(20) NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    DT_NASCIMENTO DATE,
    CONSTRAINT FK_CLIENTE_ANIMAL FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF),
    CONSTRAINT PK_COD_CPF PRIMARY KEY (CODANIMAL, CPF)
);