CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    CEP VARCHAR(8),
    NUMERO VARCHAR(4) NOT NULL
);

CREATE TABLE TELEFONE (
    CPF VARCHAR(11) PRIMARY KEY,
    TELEFONE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
);

CREATE TABLE ANIMAL (
    CODANIMAL VARCHAR(10),
    CPF VARCHAR(11),
    NOME VARCHAR(20) NOT NULL,
    RACA VARCHAR(20) NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    DT_NASCIMENTO DATE,
    CONSTRAINT FK_CLIENTE_ANIMAL FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF),
    CONSTRAINT PK_COD_CPF PRIMARY KEY (CODANIMAL, CPF)
);

CREATE TABLE CLINICA (
    CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    LOCALIZACAO VARCHAR(80) NOT NULL
);

CREATE TABLE DESCONTO (
    CUPOM VARCHAR (8) PRIMARY KEY,
    VALOR NUMBER(4,2) NOT NULL
);

CREATE TABLE CONTRATAM (
    CPF VARCHAR(11),
    CNPJ VARCHAR(14),
    CUPOM VARCHAR(8),
    CONSTRAINT PK_CPF_CNPJ PRIMARY KEY (CPF, CNPJ),
    CONSTRAINT FK_CLIENTE_CONTRATAM FOREIGN KEY (CPF) REFERENCES CLIENTE ON DELETE CASCADE,
    CONSTRAINT FK_CLINICA_CONTRATAM FOREIGN KEY (CNPJ) REFERENCES CLINICA  ON DELETE CASCADE,
    CONSTRAINT FK_DESCONTO_CONTRATAM FOREIGN KEY (CUPOM) REFERENCES DESCONTO ON DELETE CASCADE
);

CREATE TABLE EMPREGADO (
    CODEMPREGADO VARCHAR(10) PRIMARY KEY,
    CNPJ VARCHAR(14),
    TELEFONE VARCHAR(20) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    SALARIO NUMBER(8,2) NOT NULL,
    CHEFE VARCHAR(10),
    CONSTRAINT FK_CLINICA_EMPREGADO FOREIGN KEY (CNPJ) REFERENCES CLINICA ON DELETE CASCADE,
    CONSTRAINT FK_CHEFE_EMPREGADO FOREIGN KEY (CHEFE) REFERENCES EMPREGADO (CODEMPREGADO)
);

CREATE TABLE GRADUADO (
    CODEMPREGADO VARCHAR(10),
    DIPLOMA VARCHAR(80) NOT NULL,
    FUNCAO VARCHAR(80) NOT NULL,
    CONSTRAINT PK_GRADUADO PRIMARY KEY (CODEMPREGADO),
    CONSTRAINT FK_EMPREGADO_GRADUADO FOREIGN KEY (CODEMPREGADO) REFERENCES EMPREGADO ON DELETE CASCADE
);

CREATE TABLE TECNICO (
    CODEMPREGADO VARCHAR(10),
    FUNCAO VARCHAR(80) NOT NULL,
    CONSTRAINT PK_TECNICO PRIMARY KEY (CODEMPREGADO),
    CONSTRAINT FK_EMPREGADO_TECNICO FOREIGN KEY (CODEMPREGADO) REFERENCES EMPREGADO ON DELETE CASCADE
);

CREATE TABLE LOJA (
    CODLOJA VARCHAR(10) PRIMARY KEY,
    CNPJ VARCHAR(14),
    TELEFONE VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(80) NOT NULL,
    CONSTRAINT FK_CLINICA_LOJA FOREIGN KEY (CNPJ) REFERENCES CLINICA (CNPJ)
);

CREATE TABLE SERVICO (
    CODSERVICO VARCHAR(10) PRIMARY KEY,
    CODCLIENTE VARCHAR(11),
    DATASERVICO DATE NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    VALOR NUMBER(8,2) NOT NULL
);

CREATE TABLE PRODUTO (
    CODPRODUTO VARCHAR(10) PRIMARY KEY,
    MARCA VARCHAR(20) NOT NULL,
    VALORUNITARIO NUMBER(8,2) NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE OFERECEM (
    DATASERVICO DATE NOT NULL,
    CODSERVICO VARCHAR(10),
    CODPRODUTO VARCHAR(10),
    CODLOJA VARCHAR(10),
    CONSTRAINT PK_OFERECEM PRIMARY KEY (DATASERVICO, CODSERVICO, CODPRODUTO),
    CONSTRAINT FK_SERVICO_OFERECEM FOREIGN KEY (CODSERVICO) REFERENCES SERVICO ON DELETE CASCADE,
    CONSTRAINT FK_PRODUTO_OFERECEM FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO ON DELETE CASCADE,
    CONSTRAINT FK_LOJA_OFERECEM FOREIGN KEY (CODLOJA) REFERENCES LOJA ON DELETE CASCADE
);






