CREATE TABLE CLIENTE OF TP_CLIENTE(
    CPF  PRIMARY KEY,
    NOME  NOT NULL,
    ENDERECO NOT NULL,
    TELEFONES  NOT NULL
);

CREATE TABLE CLINICA OF TP_CLINICA (
    CNPJ PRIMARY KEY,
    NOME NOT NULL,
    ENDERECO NOT NULL
);

CREATE TABLE EMPREGADO OF TP_EMPREGADO (
    NOME  NOT NULL,
    CPF PRIMARY KEY,
    ENDERECO NOT NULL,
    CNPJ NOT NULL,    
    SALARIO  NOT NULL,
    TELEFONES  NOT NULL,
    CHEFE WITH ROWID REFERENCES EMPREGADO,
    CONSTRAINT FK_CLINICA_EMPREGADO FOREIGN KEY (CNPJ) REFERENCES CLINICA ON DELETE CASCADE
);

CREATE TABLE LOJA OF TP_LOJA (
    CODLOJA  PRIMARY KEY,
    CNPJ NOT NULL,
    TELEFONES  NOT NULL,
    ENDERECO NOT NULL,
    CONSTRAINT FK_CLINICA_LOJA FOREIGN KEY (CNPJ) REFERENCES CLINICA (CNPJ) ON DELETE CASCADE
);

CREATE TABLE ANIMAL (
    CODANIMAL VARCHAR(10),
    CPF VARCHAR(11),
    NOME VARCHAR(20) NOT NULL,
    RACA VARCHAR(20) NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    DT_NASCIMENTO DATE,
    CONSTRAINT FK_CLIENTE_ANIMAL FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF),
    CONSTRAINT PK_COD_CPF PRIMARY KEY (CODANIMAL, CPF)
);

CREATE TABLE DESCONTO (
    CUPOM VARCHAR (8) PRIMARY KEY,
    VALOR NUMBER(4,2) NOT NULL
);

CREATE TABLE CONTRATAM (
    CPF VARCHAR(11),
    CNPJ VARCHAR(14),
    CUPOM VARCHAR(8),
    CONSTRAINT PK_CPF_CNPJ PRIMARY KEY (CPF, CNPJ),
    CONSTRAINT FK_CLIENTE_CONTRATAM FOREIGN KEY (CPF) REFERENCES CLIENTE ON DELETE CASCADE,
    CONSTRAINT FK_CLINICA_CONTRATAM FOREIGN KEY (CNPJ) REFERENCES CLINICA  ON DELETE CASCADE,
    CONSTRAINT FK_DESCONTO_CONTRATAM FOREIGN KEY (CUPOM) REFERENCES DESCONTO ON DELETE CASCADE
);

CREATE TABLE GRADUADO (
    CODEMPREGADO VARCHAR(10),
    DIPLOMA VARCHAR(80) NOT NULL,
    FUNCAO VARCHAR(80) NOT NULL,
    CONSTRAINT PK_GRADUADO PRIMARY KEY (CODEMPREGADO),
    CONSTRAINT FK_EMPREGADO_GRADUADO FOREIGN KEY (CODEMPREGADO) REFERENCES EMPREGADO ON DELETE CASCADE
);

CREATE TABLE TECNICO (
    CODEMPREGADO VARCHAR(10),
    FUNCAO VARCHAR(80) NOT NULL,
    CONSTRAINT PK_TECNICO PRIMARY KEY (CODEMPREGADO),
    CONSTRAINT FK_EMPREGADO_TECNICO FOREIGN KEY (CODEMPREGADO) REFERENCES EMPREGADO ON DELETE CASCADE
);

CREATE TABLE SERVICO (
    CODSERVICO VARCHAR(10) PRIMARY KEY,
    CODCLIENTE VARCHAR(11),
    DATASERVICO DATE NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    VALOR NUMBER(8,2) NOT NULL
);

CREATE TABLE PRODUTO (
    CODPRODUTO VARCHAR(10) PRIMARY KEY,
    MARCA VARCHAR(20) NOT NULL,
    VALORUNITARIO NUMBER(8,2) NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE OFERECEM (
    DATASERVICO DATE NOT NULL,
    CODSERVICO VARCHAR(10),
    CODPRODUTO VARCHAR(10),
    CODLOJA VARCHAR(10),
    CONSTRAINT PK_OFERECEM PRIMARY KEY (DATASERVICO, CODSERVICO, CODPRODUTO),
    CONSTRAINT FK_SERVICO_OFERECEM FOREIGN KEY (CODSERVICO) REFERENCES SERVICO ON DELETE CASCADE,
    CONSTRAINT FK_PRODUTO_OFERECEM FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO ON DELETE CASCADE,
    CONSTRAINT FK_LOJA_OFERECEM FOREIGN KEY (CODLOJA) REFERENCES LOJA ON DELETE CASCADE
);






