-- CRIACAO DO TIPO TELEFONE
CREATE OR REPLACE TYPE tp_telefone AS OBJECT(
    telefone VARCHAR2(14) -- (XX)XXXXX-XXXX
) NOT FINAL;
/

-- CRIACAO DO TIPO TELEFONES (ATRIBUTO MULTIVALORADO - LISTA DE VARIOS TELEFONES)
CREATE OR REPLACE TYPE tp_telefones AS VARRAY(3) OF tp_telefone;
/