
-- CRIACAO DO TIPO ENDERECO
CREATE OR REPLACE TYPE TP_ENDERECO AS OBJECT(
	CEP VARCHAR2(10), -- XX.XXX-XXX
	RUA VARCHAR2(255),
    NUMERO INTEGER,
   	CIDADE VARCHAR2(255),

    MEMBER PROCEDURE EXIBIRENDERECO
);
/

-- BODY DO TIPO ENDERECO
CREATE OR REPLACE TYPE BODY TP_ENDERECO AS   
    MEMBER PROCEDURE EXIBIRENDERECO IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Endereço:');
        DBMS_OUTPUT.PUT_LINE(RUA || ', ' || TO_CHAR(NUMERO));
        DBMS_OUTPUT.PUT_LINE('CEP: ' || CEP);
        DBMS_OUTPUT.PUT_LINE(cidade);

    END;
END;
/

-- CRIACAO DO TIPO TELEFONE
CREATE OR REPLACE TYPE TP_TELEFONE AS OBJECT(
    TELEFONE VARCHAR2(14) -- (XX)XXXXX-XXXX
) NOT FINAL;
/

-- CRIACAO DO TIPO TELEFONES (ATRIBUTO MULTIVALORADO - LISTA DE VARIOS TELEFONES)
CREATE OR REPLACE TYPE TP_TELEFONES AS VARRAY(3) OF TP_TELEFONE;
/

-- CRIACAO DO TIPO PESSOA
CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    NOME VARCHAR2(255),
    CPF VARCHAR2(14), -- XXX.XXX.XXX-XX
    ENDERECO TP_ENDERECO,

    CONSTRUCTOR FUNCTION TP_PESSOA(SELF IN OUT NOCOPY TP_PESSOA, NOME VARCHAR2, CPF VARCHAR2, ENDERECO TP_ENDERECO) RETURN SELF AS RESULT,
    ORDER MEMBER FUNCTION ORDENAPORNOME(P TP_PESSOA) RETURN INTEGER,
    MEMBER FUNCTION MESMOLUGAR(P1 TP_PESSOA, P2 TP_PESSOA) RETURN BOOLEAN
) NOT FINAL;
/

-- BODY DO TIPO PESSOA
CREATE OR REPLACE TYPE BODY TP_PESSOA AS
    CONSTRUCTOR FUNCTION TP_PESSOA(SELF IN OUT NOCOPY TP_PESSOA, NOME VARCHAR2, CPF VARCHAR2, ENDERECO TP_ENDERECO) RETURN SELF AS RESULT IS
    BEGIN
        SELF.NOME:= NOME;
        SELF.CPF:= CPF;
	    RETURN;
    END;

    ORDER MEMBER FUNCTION ORDENAPORNOME(P TP_PESSOA) RETURN INTEGER IS
    BEGIN
        IF SELF.NOME > P.NOME THEN
            RETURN (1);
        ELSE
            IF SELF.NOME < P.NOME THEN
                RETURN (-1);
            ELSE
                RETURN (0);
            END IF;
        END IF;
    END;
    MEMBER FUNCTION MESMOLUGAR(P1 TP_PESSOA, P2 TP_PESSOA) RETURN BOOLEAN IS
    BEGIN
        IF P1.ENDERECO.CIDADE = P2.ENDERECO.CIDADE THEN
            RETURN (TRUE);
        ELSE 
            RETURN (FALSE);
        END IF;
    END;    
END;
/
    

-- CRIACAO DO TIPO CLIENTE (ESPECIALIZAO DE PESSOA)
CREATE OR REPLACE TYPE TP_CLIENTE UNDER TP_PESSOA(
    TELEFONES TP_TELEFONES
);
/






-- EXEMPLO CRIANDO A TABELA CLIENTE, FAZENDO UM POVOAMENTO E CONSULTANDO ALGO


CREATE TABLE CLIENTE OF TP_CLIENTE(
    CPF  PRIMARY KEY,
    NOME  NOT NULL,
    ENDERECO NOT NULL,
    TELEFONES  NOT NULL
);


INSERT INTO CLIENTE VALUES ('Tânia Dias Oliveira', '859.839.606-01', tp_endereco('24743-690', 'Rua Augusto Melo', '89', 'Recife'), tp_telefones(tp_telefone('(19)78456-2145'), tp_telefone('(19)78456-2146'), tp_telefone('(19)78456-2147')));

DECLARE
    mb TP_CLIENTE;
BEGIN 
    SELECT VALUE(c) INTO mb FROM CLIENTE C
    WHERE C.NOME = 'Tânia Dias Oliveira';
    mb.ENDERECO.EXIBIRENDERECO();
END;
